steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Setup Buildx"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Image"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx build \
          --platform linux/amd64 \
          -t us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA \
          --cache-from type=registry,ref=us-docker.pkg.dev/$PROJECT_ID/nebulous/server:buildcache \
          --cache-to type=registry,ref=us-docker.pkg.dev/$PROJECT_ID/nebulous/server:buildcache,mode=max \
          --push \
          .

  - name: "gcr.io/cloud-builders/docker"
    id: "Tag Branch"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA
        docker tag us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$BRANCH_NAME
        docker push us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$BRANCH_NAME

  - name: "gcr.io/cloud-builders/docker"
    id: "Tag Latest"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" == "main" ]; then
          docker tag us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA us-docker.pkg.dev/$PROJECT_ID/nebulous/server:latest
          docker push us-docker.pkg.dev/$PROJECT_ID/nebulous/server:latest
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: "Tag Version"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -n "$TAG_NAME" ]; then
          echo "Detected tag: $TAG_NAME. Tagging with version."
          docker tag us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$TAG_NAME
          docker push us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$TAG_NAME
        else
          echo "No TAG_NAME detected. Skipping version tag."
        fi

timeout: "1800s"

options:
  machineType: "N1_HIGHCPU_8"
  env:
    - DOCKER_BUILDKIT=1