services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # No password
    ports:
      - "5432:5432"

  nebu:
    # image: us-docker.pkg.dev/agentsea-dev/nebulous/server:${NEBU_VERSION:-latest}
    image: us-docker.pkg.dev/agentsea-dev/nebulous/server:latest
    container_name: nebu
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/postgres
      RUST_LOG: debug
      NEBU_BUCKET_NAME: nebulous
      NEBU_BUCKET_REGION: us-east-1
      NEBU_ROOT_OWNER: me
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: nebulous
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_AUTH_KEY=
      - TS_EXTRA_ARGS=--login-server https://headscale.nebulous.sh
    volumes:
      - nebu-ts-authkey:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - nebu-ts-sock:/var/run/tailscale
      - nebu-tmp:/tmp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

volumes:
  sccache:
  nebu-ts-authkey:
    driver: local
  nebu-ts-sock:
    driver: local
  nebu-tmp:
    driver: local
