{{- if or .Values.bucket.auth.accessKeyId .Values.bucket.auth.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bucket.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.bucket.secret.keys.accessKeyId }}: {{ required ".Values.bucket.auth.accessKeyId is required" .Values.bucket.auth.accessKeyId | b64enc }}
  {{ .Values.bucket.secret.keys.secretAccessKey }}: {{ required ".Values.bucket.auth.secretAccessKey is required" .Values.bucket.auth.secretAccessKey | b64enc }}
{{- end }}
