{{- if default false .Values.encryptionKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulous.encryptionKeySecretName" . }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "nebulous.encryptionKeySecretKey" . }}: {{ .Values.encryptionKey.encodedValue }}
{{- end }}