{{- if .Values.encryptionKey.encodedValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.encryptionKey.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.encryptionKey.secret.keys.encryptionKey }}: {{ .Values.encryptionKey.encodedValue }}
{{- end }}
