{{- if .Values.headscale.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale.name" . }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |
    server_url: {{ printf "https://%s:443" .Values.headscale.domain }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    noise:
      private_key_path: /mnt/keys/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    {{- if .Values.headscale.tls.letsencrypt.hostname }}
    tls_letsencrypt_hostname: {{ .Values.headscale.tls.letsencrypt.hostname }}
    acme_email: {{ .Values.headscale.tls.letsencrypt.email }}
    tls_letsencrypt_listen: ":http"
    tls_letsencrypt_cache_dir: /mnt/letsencrypt
    tls_letsencrypt_challenge_type: HTTP-01
    {{- end }}
    tls_cert_path: ""
    tls_key_path: ""
    database:
      type: sqlite
    derp:
      server:
        enabled: false
    {{- with .Values.headscale.derp.externalMaps }}
      urls: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.headscale.derp.configMap.name }}
      paths:
        - /mnt/derp/{{ .Values.headscale.derp.configMap.key }}
    {{- end }}
    dns:
      base_domain: {{ .Values.headscale.dns.baseDomain }}
    log:
      format: {{ .Values.headscale.log.format }}
      level: {{ .Values.headscale.log.level }}
---
{{- if .Values.headscale.sqlite.createPersistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.headscale.sqlite.claimName }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- with .Values.headscale.sqlite.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.headscale.sqlite.size }}
---
{{- end }}
{{- if .Values.headscale.privateKeys.createPersistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.headscale.privateKeys.claimName }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- with .Values.headscale.privateKeys.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.headscale.privateKeys.size }}
---
{{- end }}
{{- if and .Values.headscale.tls.letsencrypt.hostname .Values.headscale.tls.letsencrypt.createPersistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.headscale.tls.letsencrypt.claimName }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- with .Values.headscale.tls.letsencrypt.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.headscale.tls.letsencrypt.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headscale.name" . }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "headscale.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "headscale.name" . }}
    spec:
      containers:
        - name: headscale
          image: "headscale/headscale:{{ .Values.headscale.imageTag }}"
          command:
            - headscale
            - serve
          ports:
            - containerPort: 8080
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/headscale
              name: config
            - mountPath: /mnt/sqlite
              name: sqlite
            - mountPath: /mnt/keys
              name: private-keys
            {{- if .Values.headscale.tls.letsencrypt.hostname }}
            - mountPath: /mnt/letsencrypt
              name: tls-letsencrypt
            {{- end }}
            {{- if .Values.headscale.derp.configMap.name }}
            - mountPath: /mnt/derp
              name: derp-config
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "headscale.name" . }}
        - name: sqlite
          persistentVolumeClaim:
            claimName: {{ .Values.headscale.sqlite.claimName }}
        - name: private-keys
          persistentVolumeClaim:
            claimName: {{ .Values.headscale.privateKeys.claimName }}
        {{- if .Values.headscale.tls.letsencrypt.hostname }}
        - name: tls-letsencrypt
          persistentVolumeClaim:
            claimName: {{ .Values.headscale.tls.letsencrypt.claimName }}
        {{- end }}
        {{- if .Values.headscale.derp.configMap.name }}
        - name: derp-config
          configMap:
            name: {{ .Values.headscale.derp.configMap.name }}
        {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/exec" ]
    verbs: [ "get", "list", "watch", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-exec
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nebulous.serviceAccountName" . }}
    namespace: {{ include "nebulous.namespace" . }}
roleRef:
  kind: Role
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-management
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-management
  namespace: {{ include "nebulous.namespace" . }}
  labels:
      {{- include "common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nebulous.serviceAccountName" . }}
    namespace: {{ include "nebulous.namespace" . }}
roleRef:
  kind: Role
  name: secret-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.serviceName" . }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.headscale.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ include "headscale.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.headscale.service.port }}
      targetPort: 8080
  type: {{ .Values.headscale.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.name" . }}-metrics
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "headscale.name" . }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
{{- if .Values.headscale.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "headscale.serviceName" . }}
  namespace: {{ include "headscale.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.headscale.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.headscale.ingress.ingressClassName }}
  ingressClassName: {{.}}
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "headscale.serviceName" . }}
      port:
        number: {{ .Values.headscale.service.port }}
{{- end }}
{{- end }}
