{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ include "nebulous.namespace" . }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{.}}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "nebulous.serviceName" . }}
                port:
                  number: {{ include "nebulous.servicePort" . }}
            path: /
            pathType: Prefix
{{- end }}