apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  connection_string: {{ printf "postgresql://%s:%s@%s:%s/%s" (include "postgres.user" .) (include "postgres.password" .) (include "postgres.host" .) (include "postgres.port" .) (include "postgres.database" .) | b64enc }}
---
{{- if default false .Values.postgres.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ include "postgres.database" . }}
            - name: POSTGRES_USER
              value: {{ include "postgres.user" . }}
            - name: POSTGRES_PASSWORD
              value: {{ include "postgres.password" . }}
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{- default "postgres-pvc" .Values.postgres.persistence.claimName }}
          {{- else }}
          emptyDir: {}
          {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ include "postgres.port" . }}
      targetPort: 5432
  type: ClusterIP
---
{{- if default false .Values.postgres.persistence.createPersistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{- default "postgres-pvc" .Values.postgres.persistence.claimName }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: {{- .Values.postgres.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{- default "100Gi" .Values.postgres.persistence.size }}
{{- end}}
{{- end }}
