{{- if .Values.providers.runpod.enabled }}
{{- if .Values.providers.runpod.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.providers.runpod.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.providers.runpod.secret.keys.apiKey }}: {{ .Values.providers.runpod.auth.apiKey | b64enc }}
{{- end }}
{{- end }}
