{{- if or (not .Values.redis.secret) .Values.redis.create }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  connection_string: {{ printf "redis://%s:%s/%s" (include "redis.host" .) (include "redis.port" .) (include "redis.database" . ) | b64enc }}
  password: {{ include "redis.password" . | b64enc }}
---
{{- end }}
{{- if default false .Values.redis.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis:{{ default "latest" .Values.redis.imageTag }}"
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec redis-server --requirepass "$REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default "redis-secret" .Values.redis.secret.name }}
                  key: {{ default "password" .Values.redis.secret.keys.password }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ include "redis.port" . }}
      targetPort: 6379
  type: ClusterIP
---
{{- if .Values.redis.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "redis.serviceName" . }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.redis.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.redis.ingress.className }}
  ingressClassName: {{.}}
  {{- end }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "redis.serviceName" . }}
                port:
                  number: {{ include "redis.port" . }}
            path: /
            pathType: Prefix
      {{- with .Values.ingress.host }}
      host: {{.}}
      {{- end }}
{{- end }}
{{- end }}
