{{- if or .Values.redis.auth.host .Values.redis.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.secret.keys.connectionString }}: {{ printf "redis://:%s@%s:%d/%d" .Values.redis.auth.password (include "redis.host" .) (int .Values.redis.auth.port) (int .Values.redis.auth.database) | b64enc }}
  {{ .Values.redis.secret.keys.password}}: {{ .Values.redis.auth.password | b64enc }}
  {{ .Values.redis.secret.keys.publicConnectionString }}: {{ printf "redis://:%s@%s:%d/%d" .Values.redis.auth.password (include "redis.publicHost" .) (int .Values.redis.auth.port) (int .Values.redis.auth.database) | b64enc }}
---
{{- end }}
{{- if and .Values.redis.tailscale.authKey (not .Values.headscale.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.tailscale.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.tailscale.secret.keys.authKey }}: {{ required ".Values.redis.tailscale.authKey is required" .Values.tailscale.authKey | b64enc }}
---
{{- end }}
{{- if .Values.redis.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccountName }}
---
# Reference: https://github.com/tailscale/tailscale/blob/main/docs/k8s/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-{{ .Values.redis.serviceAccountName }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: ["{{ include "redis.tailscaleStateSecretName" . }}"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-{{ .Values.redis.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.redis.serviceAccountName }}
roleRef:
  kind: Role
  name: tailscale-redis
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.name" . }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ include "redis.name" . }}
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "redis.name" . }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ include "redis.name" . }}
        app.kubernetes.io/component: cache
        app: {{ include "redis.name" . }}
    spec:
      serviceAccountName: {{ .Values.redis.serviceAccountName }}
      containers:
        - name: redis
          image: "redis:{{ .Values.redis.imageTag }}"
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec redis-server --requirepass "$REDIS_PASSWORD"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secret.name }}
                  key: {{ .Values.redis.secret.keys.password }}
          ports:
            - containerPort: 6379
          {{- with .Values.redis.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
        # Reference: https://github.com/tailscale/tailscale/blob/main/docs/k8s/userspace-sidecar.yaml
        # Docs: https://tailscale.com/kb/1185/kubernetes
        - name: tailscale
          image: "tailscale/tailscale:{{ .Values.tailscale.imageTag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.tailscale.secret.name }}
                  key: {{ .Values.redis.tailscale.secret.keys.authKey }}
            - name: TS_HOSTNAME
              value: {{ include "redis.name" . }}
            - name: TS_EXTRA_ARGS
              value: --login-server {{ include "tailscale.loginServer" . }}
            - name: TS_KUBE_SECRET
              value: {{ include "redis.tailscaleStateSecretName" . }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          {{- with .Values.redis.tailscale.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.serviceName" . }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.redis.service.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ include "redis.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.auth.port }}
      targetPort: 6379
  type: ClusterIP
{{- end }}
