apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tailscale.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tailscale.secret.keys.host }}: {{ include "tailscale.host"  . | b64enc }}
