{{- if and (or .Values.tailscale.apiKey .Values.tailscale.authKey) (not .Values.headscale.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tailscale.secret.name }}
  namespace: {{ include "nebulous.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tailscale.secret.keys.apiKey }}: {{ required ".Values.tailscale.apiKey is required" .Values.tailscale.apiKey | b64enc }}
  {{ .Values.tailscale.secret.keys.authKey }}: {{ required ".Values.tailscale.authKey is required" .Values.tailscale.authKey | b64enc }}
---
{{- end }}
# Reference: https://github.com/tailscale/tailscale/blob/main/docs/k8s/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-{{ include "nebulous.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: ["{{ include "nebulous.tailscaleStateSecretName" . }}"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-nebu
subjects:
  - kind: ServiceAccount
    name: {{ include "nebulous.serviceAccountName" . }}
roleRef:
  kind: Role
  name: tailscale-{{ include "nebulous.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
